import { Schema, model, Document, Types } from 'mongoose';

export interface IRuleCondition {
  field: 'sender' | 'subject' | 'body';
  operator: 'contains' | 'equals' | 'startsWith' | 'regex';
  value: string;
}

export interface IRule extends Document {
  categoryId: Types.ObjectId;
  conditions: IRuleCondition[];
  priority: number;
  autoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const RuleConditionSchema = new Schema<IRuleCondition>(
  {
    field: { type: String, enum: ['sender', 'subject', 'body'], required: true },
    operator: { type: String, enum: ['contains', 'equals', 'startsWith', 'regex'], required: true },
    value: { type: String, required: true, trim: true }
  },
  { _id: false }
);

const RuleSchema = new Schema<IRule>(
  {
    categoryId: { type: Schema.Types.ObjectId, ref: 'Category', required: true },
    conditions: { type: [RuleConditionSchema], required: true },
    priority: { type: Number, default: 10 },
    autoGenerated: { type: Boolean, default: false }
  },
  { timestamps: true }
);

export const RuleModel = model<IRule>('Rule', RuleSchema);
