import { RuleModel, IRule } from '../models/Rule.js';
import { CategoryModel } from '../models/Category.js';
import { Types } from 'mongoose';

export class RuleEngine {
  public static async evaluateEmail(
    sender: string,
    subject: string,
    body: string
  ): Promise<Types.ObjectId | null> {
    const rules = await RuleModel.find({}).sort({ priority: -1 }).lean();

    for (const rule of rules) {
      const isMatch = rule.conditions.every((condition) => {
        let targetValue = '';
        if (condition.field === 'sender') targetValue = sender;
        else if (condition.field === 'subject') targetValue = subject;
        else if (condition.field === 'body') targetValue = body;

        const valLower = targetValue.toLowerCase();
        const condValLower = condition.value.toLowerCase();

        switch (condition.operator) {
          case 'contains':
            return valLower.includes(condValLower);
          case 'equals':
            return valLower === condValLower;
          case 'startsWith':
            return valLower.startsWith(condValLower);
          case 'regex':
            try {
              const regex = new RegExp(condition.value, 'i');
              return regex.test(targetValue);
            } catch {
              return false;
            }
          default:
            return false;
        }
      });

      if (isMatch) {
        return rule.categoryId as Types.ObjectId;
      }
    }

    return null;
  }

  public static async autoGenerateRuleFromUserFeedback(
    subject: string,
    sender: string,
    categoryId: Types.ObjectId
  ): Promise<IRule> {
    // Extract key distinguishing word from subject or sender
    const cleanSubject = subject.replace(/re:|fw:|fwd:/gi, '').trim();
    const words = cleanSubject.split(/\s+/).filter((w) => w.length > 3);
    const primaryKeyword = words[0] || sender.split('@')[0] || 'mail';

    const newRule = new RuleModel({
      categoryId,
      conditions: [
        {
          field: 'subject',
          operator: 'contains',
          value: primaryKeyword
        }
      ],
      priority: 5,
      autoGenerated: true
    });

    await newRule.save();
    return newRule;
  }
}
