import { Request, Response } from 'express';
import { RuleModel } from '../models/Rule.js';

export class RuleController {
  public static async getRules(_req: Request, res: Response) {
    try {
      const rules = await RuleModel.find({}).populate('categoryId').sort({ priority: -1 });
      res.json({ success: true, count: rules.length, data: rules });
    } catch (error: any) {
      res.status(500).json({ success: false, error: error.message });
    }
  }

  public static async createRule(req: Request, res: Response) {
    try {
      const { categoryId, conditions, priority } = req.body;
      if (!categoryId || !conditions || !Array.isArray(conditions) || conditions.length === 0) {
        return res.status(400).json({ success: false, error: 'Category ID and valid conditions are required' });
      }

      const rule = new RuleModel({
        categoryId,
        conditions,
        priority: priority || 10,
        autoGenerated: false
      });

      await rule.save();
      const populatedRule = await RuleModel.findById(rule._id).populate('categoryId');
      res.status(201).json({ success: true, data: populatedRule });
    } catch (error: any) {
      res.status(500).json({ success: false, error: error.message });
    }
  }

  public static async deleteRule(req: Request, res: Response) {
    try {
      const { id } = req.params;
      await RuleModel.findByIdAndDelete(id);
      res.json({ success: true, message: 'Rule deleted successfully' });
    } catch (error: any) {
      res.status(500).json({ success: false, error: error.message });
    }
  }
}
