import { Request, Response } from 'express';
import mongoose from 'mongoose';
import { RuleModel } from '../models/Rule';

const MOCK_RULES = [
  { _id: 'r1', categoryId: { name: 'Invoices & Receipts' }, conditions: [{ field: 'subject', operator: 'contains', value: 'Invoice' }], priority: 10, autoGenerated: false },
  { _id: 'r2', categoryId: { name: 'Alerts & Security' }, conditions: [{ field: 'subject', operator: 'contains', value: 'Security' }], priority: 10, autoGenerated: false }
];

export class RuleController {
  public static async getRules(_req: Request, res: Response) {
    try {
      if (mongoose.connection.readyState !== 1) {
        return res.json({ success: true, count: MOCK_RULES.length, data: MOCK_RULES });
      }
      const rules = await RuleModel.find({}).populate('categoryId').sort({ priority: -1 });
      res.json({ success: true, count: rules.length, data: rules });
    } catch (error: any) {
      res.json({ success: true, count: MOCK_RULES.length, data: MOCK_RULES });
    }
  }

  public static async createRule(req: Request, res: Response) {
    try {
      const { categoryId, conditions, priority } = req.body;
      if (!categoryId || !conditions || !Array.isArray(conditions) || conditions.length === 0) {
        return res.status(400).json({ success: false, error: 'Category ID and valid conditions are required' });
      }

      if (mongoose.connection.readyState !== 1) {
        return res.status(201).json({ success: true, data: { _id: `r_${Date.now()}`, categoryId, conditions, priority: priority || 10 } });
      }

      const rule = new RuleModel({
        categoryId,
        conditions,
        priority: priority || 10,
        autoGenerated: false
      });

      await rule.save();
      const populatedRule = await RuleModel.findById(rule._id).populate('categoryId');
      res.status(201).json({ success: true, data: populatedRule });
    } catch (error: any) {
      res.status(500).json({ success: false, error: error.message });
    }
  }

  public static async deleteRule(req: Request, res: Response) {
    try {
      const { id } = req.params;
      if (mongoose.connection.readyState === 1) {
        await RuleModel.findByIdAndDelete(id);
      }
      res.json({ success: true, message: 'Rule deleted successfully' });
    } catch (error: any) {
      res.status(500).json({ success: false, error: error.message });
    }
  }
}
