export interface Category {
  _id: string;
  name: string;
  slug: string;
  colorCode: string;
  createdSource: 'SYSTEM' | 'USER';
}

export interface EmailRecord {
  _id: string;
  messageId: string;
  sender: string;
  subject: string;
  rawTextBody: string;
  parsedJson: Record<string, any>;
  hasAttachments: boolean;
  ocrExtractedText?: string;
  categoryId?: Category;
  categorySource: 'RULE' | 'GROQ_AI' | 'USER_MANUAL' | 'UNASSIGNED';
  aiConfidenceScore?: number;
  needsUserReview: boolean;
  reviewStatus: 'PENDING' | 'APPROVED' | 'REASSIGNED';
  receivedAt: string;
  processedAt: string;
}

export interface Rule {
  _id: string;
  categoryId: Category;
  conditions: Array<{
    field: 'sender' | 'subject' | 'body';
    operator: 'contains' | 'equals' | 'startsWith' | 'regex';
    value: string;
  }>;
  priority: number;
  autoGenerated: boolean;
}

export interface DashboardStats {
  summary: {
    totalEmails: number;
    pendingReviews: number;
    totalFinancialAmount: number;
    sources: {
      rule: number;
      ai: number;
      user: number;
    };
    aiAccuracyPercentage: number;
  };
  categoryBreakdown: Array<{
    categoryName: string;
    colorCode: string;
    count: number;
  }>;
}
